# http://module-build.sourceforge.net/META-spec.html
name:         File-MergeSort
version:      1.13
version_from: MergeSort.pm
installdirs:  site
license:      perl
requires:
    IO::File:                      0
    Test::More:                    0
recommends:
    IO::Zlib                       0
    Test::Pod::Coverage            1.00
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
