--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
name:         File-MergeSort
version:      1.14
version_from: MergeSort.pm
installdirs:  site
license:      perl
requires:
    IO::File:                      0
    Test::More:                    0
recommends:
    IO::Zlib                       0
    Test::Pod::Coverage            1.00
    Test::Pod                      1.00
distribution_type: module
generated_by: hand
